# Generated by Django 3.2.8 on 2021-10-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
                ('price', models.FloatField()),
            ],
        ),
    ]
